name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build, Deploy to S3 bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: npm install -g pnpm
        run: npm install -g pnpm

      - name: pnpm install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Transfer to S3 for serving static
        uses: sorin0404/github-action-test-react@main
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: sorin-github-action-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
